# Generated by Django 4.2.1 on 2023-05-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GerenteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('office_gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GerenteApp.office')),
            ],
        ),
    ]
