# Generated by Django 4.2.1 on 2023-05-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcesionariaApp', '0003_alter_gerente_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name=200)),
                ('name', models.CharField(verbose_name=200)),
                ('phone', models.CharField(verbose_name=200)),
                ('password', models.CharField(verbose_name=200)),
            ],
        ),
    ]
